version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clair

volumes:
  redis-data:

